services:
  api:
    build:
      context: .
      dockerfile: Ba7besh.Api/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DB_HOST=db
      - DB_USER=ba7besh
      - DB_PASSWORD=ba7besh_local_dev
      - DB_NAME=ba7besh
    volumes:
      - ./Ba7besh.Api/Secrets:/app/Secrets:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  db:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_USER=ba7besh
      - POSTGRES_PASSWORD=ba7besh_local_dev
      - POSTGRES_DB=ba7besh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ba7besh"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: